name: KNN_Environment
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.4
  - pip=22.2.2
  - scikit-learn=1.1.2
  - matplotlib=3.5.3
  - seaborn=0.11.2
  - plotly=5.8.2
  - pillow=9.2.0
  - pip:
      - wandb==0.13.2